export const news = [
  {slug:'ai-and-isis-planning',category:'বিশ্ব',title:'এআই দিয়ে বোমা বানানো ও হামলার পরিকল্পনা করছে আইএস-সমর্থকরা',summary:'ইত্তেফাকের প্রতিবেদনে বলা হয়েছে, কৃত্রিম বুদ্ধিমত্তা প্রযুক্তি ব্যবহার করে আইএস-সমর্থকরা হামলার পরিকল্পনা ও বিভিন্ন কৌশল নির্ধারণের চেষ্টা করছে।',image:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',date:'২৫ সেপ্টেম্বর ২০২৬',source:'দৈনিক ইত্তেফাক',sourceUrl:'https://www.ittefaq.com.bd/archive'},
  {slug:'sindhel-thief-career-change',category:'সারাদেশ',title:'টাকা-পয়সার বদলে পাচ্ছিলেন চেক বই, বিরক্ত হয়ে পেশা বদলালেন সিঁধেল চোর',summary:'প্রায় ১৮ বছর ধরে চুরি করা এক ব্যক্তির অভিজ্ঞতা নিয়ে ইত্তেফাকের প্রতিবেদনে উঠে এসেছে কীভাবে চুরির সময় নগদের বদলে চেকবই পেয়ে তিনি পেশা বদলের সিদ্ধান্ত নেন।',image:'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=80',date:'২৫ সেপ্টেম্বর ২০২৬',source:'দৈনিক ইত্তেফাক',sourceUrl:'https://www.ittefaq.com.bd/archive'},
  {slug:'biman-bangladesh-boeing-11',category:'জাতীয়',title:'বোয়িং থেকে আরও ১১ উড়োজাহাজ কিনছে বিমান বাংলাদেশ, কোন মডেলের কতটি',summary:'বিমান বাংলাদেশ এয়ারলাইন্স বহর সম্প্রসারণের পরিকল্পনার অংশ হিসেবে আরও ১১টি উড়োজাহাজ কেনার বিষয়ে ইত্তেফাকের প্রতিবেদনে তথ্য দেওয়া হয়েছে।',image:'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80',date:'২৫ সেপ্টেম্বর ২০২৬',source:'দৈনিক ইত্তেফাক',sourceUrl:'https://www.ittefaq.com.bd/archive'},
  {slug:'universal-card-plan',category:'জাতীয়',title:'জাতিসংঘে ‘ইউনিভার্সাল কার্ড’ চালুর পরিকল্পনার কথা জানালেন প্রধানমন্ত্রী',summary:'দেশের বিভিন্ন সামাজিক সুরক্ষা কর্মসূচিকে সমন্বয় করে ভবিষ্যতে একটি ইউনিভার্সাল কার্ড চালুর পরিকল্পনার কথা জাতিসংঘে তুলে ধরা হয়েছে।',image:'https://images.unsplash.com/photo-1521295121783-8a321d551ad2?auto=format&fit=crop&w=1200&q=80',date:'২৫ সেপ্টেম্বর ২০২৬',source:'দৈনিক ইত্তেফাক',sourceUrl:'https://www.ittefaq.com.bd/archive'},
  {slug:'eight-districts-storm-rain',category:'জাতীয়',title:'দুপুরের মধ্যে ৮ জেলায় ঝড়বৃষ্টির আভাস, নদীবন্দরে ১ নম্বর সতর্কসংকেত',summary:'আবহাওয়া-সংক্রান্ত পূর্বাভাসে দেশের আট জেলার ওপর দিয়ে অস্থায়ীভাবে দমকা বা ঝোড়ো হাওয়া ও বৃষ্টির সম্ভাবনার কথা জানানো হয়েছে।',image:'https://images.unsplash.com/photo-1501691223387-dd0500403074?auto=format&fit=crop&w=1200&q=80',date:'২৫ সেপ্টেম্বর ২০২৬',source:'দৈনিক ইত্তেফাক',sourceUrl:'https://www.ittefaq.com.bd/archive'},
  {slug:'debate-for-world-peace',category:'জাতীয়',title:'মারণাস্ত্র নয়, বিশ্বশান্তি প্রতিষ্ঠার হাতিয়ার হবে যুক্তিতর্ক: জাতিসংঘে তারেক রহমান',summary:'জাতিসংঘে দেওয়া বক্তব্যে বিশ্ব পরিবর্তনের ক্ষেত্রে মারণাস্ত্রের বদলে যুক্তি, কূটনীতি, শিক্ষা ও মানবতাকে গুরুত্ব দেওয়ার আহ্বান জানানো হয়েছে।',image:'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=1200&q=80',date:'২৫ সেপ্টেম্বর ২০২৬',source:'দৈনিক ইত্তেফাক',sourceUrl:'https://www.ittefaq.com.bd/archive'},
  {slug:'three-r-recovery-restoration-reform',category:'জাতীয়',title:'দেশ মেরামতে থ্রি-আর কৌশলের কথা জানালেন প্রধানমন্ত্রী',summary:'ইত্তেফাকের প্রতিবেদনে সরকারের দেশ পুনরুদ্ধার ও পুনর্গঠনের পরিকল্পনায় রিকভারি, রেস্টোরেশন ও সংশ্লিষ্ট নীতির কথা তুলে ধরা হয়েছে।',image:'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80',date:'২৫ সেপ্টেম্বর ২০২৬',source:'দৈনিক ইত্তেফাক',sourceUrl:'https://www.ittefaq.com.bd/archive'},
  {slug:'un-as-center-of-understanding',category:'জাতীয়',title:'সমঝোতামূলক বিশ্ব সমাজ প্রতিষ্ঠার কেন্দ্রবিন্দু হিসেবে জাতিসংঘকে দেখতে চায় বাংলাদেশ',summary:'আন্তর্জাতিক সহযোগিতা ও সমঝোতার মাধ্যমে বিশ্ব সমাজ গঠনে জাতিসংঘের ভূমিকার ওপর বাংলাদেশের প্রত্যাশার কথা প্রতিবেদনে তুলে ধরা হয়েছে।',image:'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=1200&q=80',date:'২৫ সেপ্টেম্বর ২০২৬',source:'দৈনিক ইত্তেফাক',sourceUrl:'https://www.ittefaq.com.bd/archive'},
  {slug:'child-safety-key',category:'রাজধানী',title:'সন্তানের হাতে ‘মৃত্যুর চাবি’',summary:'সন্তানদের চলাফেরা ও বাইরে যাতায়াতের নিরাপত্তা নিয়ে অভিভাবকদের সচেতনতার প্রয়োজনীয়তা তুলে ধরা একটি প্রতিবেদন প্রকাশ করেছে ইত্তেফাক।',image:'https://images.unsplash.com/photo-1504159506876-f8338247a14a?auto=format&fit=crop&w=1200&q=80',date:'২৫ সেপ্টেম্বর ২০২৬',source:'দৈনিক ইত্তেফাক',sourceUrl:'https://www.ittefaq.com.bd/archive'},
  {slug:'why-blind-despite-eyes',category:'মতামত',title:'চোখ থাকিতে অন্ধ কেন?',summary:'ইত্তেফাকের সম্পাদকীয়তে সামাজিক বাস্তবতা ও নানা অনিয়মের প্রতি মানুষের উদাসীনতা নিয়ে প্রশ্ন তোলা হয়েছে।',image:'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80',date:'২৫ সেপ্টেম্বর ২০২৬',source:'দৈনিক ইত্তেফাক',sourceUrl:'https://www.ittefaq.com.bd/archive'}
];
export function getNews(slug){ return news.find(n => n.slug === slug); }
